%MATLAB code for to read the signal sample value which are generated by C CODE

clc; 
clear all; 

% read the sample value 

a = readmatrix('file signal.txt'); 

%plot that FM Signal 

plot(a(1:4000)); 
xlabel("Time") 
ylabel("Amplitude") 
title("FM Modulation") 
